# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('email_contact', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_text', models.TextField()),
                ('header_title', models.CharField(max_length=120)),
                ('header_subtitle', models.CharField(max_length=300)),
                ('header_citation', models.CharField(max_length=200)),
            ],
        ),
    ]
