# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpdb_core', '0003_targetgene'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primer_for_seq', models.CharField(max_length=100)),
                ('primer_rev_seq', models.CharField(max_length=100)),
                ('target_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdb_core.TargetGene')),
            ],
        ),
    ]
