# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpdb_core', '0004_primerpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='group_website',
            field=models.URLField(default='ddg.biol.uw.edu.pl'),
            preserve_default=False,
        ),
    ]
