# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpdb_core', '0005_contact_group_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_url', models.URLField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
