# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpdb_core', '0007_home_to_notify_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileLink',
        ),
        migrations.RemoveField(
            model_name='primerpair',
            name='target_gene',
        ),
        migrations.RemoveField(
            model_name='targetgene',
            name='antibiotic_class',
        ),
        migrations.RemoveField(
            model_name='home',
            name='to_notify_email',
        ),
        migrations.DeleteModel(
            name='AntibioticClass',
        ),
        migrations.DeleteModel(
            name='PrimerPair',
        ),
        migrations.DeleteModel(
            name='TargetGene',
        ),
    ]
