# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntibioticClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ARGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('antibiotic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdb_args.AntibioticClass')),
            ],
        ),
        migrations.CreateModel(
            name='ARGPrimerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primer_for_seq', models.CharField(max_length=100)),
                ('primer_rev_seq', models.CharField(max_length=100)),
                ('ar_gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpdb_args.ARGene')),
            ],
        ),
    ]
