# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpdb_args', '0003_auto_20180517_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputfile',
            name='times_checked',
            field=models.IntegerField(default=0),
        ),
    ]
